ignoreScripts: true

minimumReleaseAge: 2880

# NOTE: 2026-08-26 11:21 JST以降に削除
minimumReleaseAgeExclude:
  - '@nuxt/icon'
  - '@nuxt/devtools-kit'

overrides:
  '@hono/node-server': '>=1.19.15'
  c12: ^3.3.2
  effect: '>=3.20.0'
  hono: '>=4.12.34'
  lodash: '>=4.18.0'
  next@>=13.4.0 <14.1.1: '>=14.1.1'
  next@>=10.0.0 <14.2.7: '>=14.2.7'
  next@>=13.0 <14.2.30: '>=14.2.30'
  next@>=0.9.9 <14.2.31: '>=14.2.31'
  next@>=9.5.5 <14.2.15: '>=14.2.15'
  next@>=0.9.9 <14.2.32: '>=14.2.32'
  next@>=0.9.9 <14.2.24: '>=14.2.24'
  valibot: '>=1.4.2'
