import 'dotenv/config';
import { Client } from 'pg';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) {
  console.error('DATABASE_URL is not set. Add it to .env');
  process.exit(1);
}

const OUTPUT = resolve(
  process.cwd(),
  'scripts/migration-data/article_likes.sql',
);
// D1 の import API は 1 ステートメントが大きいと 7500 internal error を返しがち。
// 小さめに刻んで多数のステートメントに分割する。
const BATCH_SIZE = 25;

type Row = {
  id: string;
  content_id: string;
  user_ip: string;
  secret: string | null;
  created_at: Date | string;
  updated_at: Date | string;
};

const sqlQuote = (v: string) => `'${v.replace(/'/g, "''")}'`;
const toIso = (d: Date | string) =>
  (d instanceof Date ? d : new Date(d)).toISOString();

async function main() {
  const client = new Client({ connectionString: DATABASE_URL });
  await client.connect();

  const { rows } = await client.query<Row>(
    'SELECT id, content_id, user_ip, secret, created_at, updated_at FROM article_likes ORDER BY created_at ASC',
  );
  await client.end();

  console.log(`Fetched ${rows.length} rows from CockroachDB`);

  const out: string[] = [
    '-- Auto-generated by scripts/migrate-cockroach-to-d1.ts',
    `-- Source rows: ${rows.length}`,
    `-- Generated at: ${new Date().toISOString()}`,
    '',
  ];

  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE);
    const values = batch.map((r) => {
      const secret = r.secret === null ? 'NULL' : sqlQuote(r.secret);
      return `  (${sqlQuote(r.id)}, ${sqlQuote(r.content_id)}, ${sqlQuote(r.user_ip)}, ${secret}, ${sqlQuote(toIso(r.created_at))}, ${sqlQuote(toIso(r.updated_at))})`;
    });
    out.push(
      'INSERT OR IGNORE INTO article_likes (id, content_id, user_ip, secret, created_at, updated_at) VALUES',
    );
    out.push(values.join(',\n') + ';');
    out.push('');
  }

  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, out.join('\n'), 'utf8');

  console.log(`Wrote ${OUTPUT}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
