import "dotenv/config";
import { existsSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { generateJSON } from "@tiptap/html";
import * as cheerio from "cheerio";
import { createCmsExtensions } from "../shared/tiptap/extensions";
import {
  countContentCharacters,
  extractPlainText,
  generateSummary,
} from "../shared/utils/tiptap-text";

// microCMSエクスポート(JSON) + image-map.json → cms_seed.sql生成
// 事前にscripts/migrate-microcms-images.tsを実行

const DATA_DIR = resolve(process.cwd(), "scripts/migration-data");
const OUTPUT = resolve(DATA_DIR, "cms_seed.sql");

interface MicroCMSTag {
  id: string;
  name: string;
  slug: string;
  createdAt: string;
  updatedAt: string;
}

interface MicroCMSArticle {
  id: string;
  title: string;
  content: string;
  eyecatch?: { url: string; width?: number; height?: number };
  tags?: MicroCMSTag[];
  is_no_index?: boolean;
  createdAt: string;
  updatedAt: string;
  publishedAt?: string;
}

const readJson = <T>(name: string): T =>
  JSON.parse(readFileSync(resolve(DATA_DIR, name), "utf8"));

const articles = readJson<MicroCMSArticle[]>("microcms-articles.json");
const tags = readJson<MicroCMSTag[]>("microcms-tags.json");
const global = readJson<{ pinned_articles?: { id: string }[] }>(
  "microcms-global.json",
);
const imageMap = readJson<Record<string, string>>("image-map.json");

const extensions = createCmsExtensions();

const rewriteImageUrl = (url: string) => {
  const key = imageMap[url];
  return key ? `/images/r2/${key}` : url;
};

// microCMS HTMLをparseHTML定義が解釈できる形へ正規化
const normalizeHtml = (html: string) => {
  const $ = cheerio.load(html, null, false);

  // div[data-filename]ラッパをpreの属性へ移動
  $("div[data-filename]").each((_, element) => {
    const $div = $(element);
    const filename = $div.attr("data-filename");
    const $pre = $div.find("pre").first();
    if (filename && $pre.length > 0) {
      $pre.attr("data-filename", filename);
    }
    $div.replaceWith($div.html() ?? "");
  });

  // text==hrefのリンクをリンクカードへ
  const isCardAnchor = (node: cheerio.Element): boolean => {
    if (node.type !== "tag" || node.tagName !== "a") return false;
    const $a = $(node);
    const href = ($a.attr("href") ?? "").trim();
    return href !== "" && $a.text().trim() === href;
  };

  $("p").each((_, element) => {
    const $p = $(element);
    if ($p.find("a").toArray().filter(isCardAnchor).length === 0) return;

    const parts: string[] = [];
    let buffer = "";
    const flush = () => {
      const trimmed = buffer
        .replace(/^(?:\s|<br\s*\/?>)+/, "")
        .replace(/(?:\s|<br\s*\/?>)+$/, "");
      const hasContent =
        cheerio.load(trimmed, null, false).text().trim() !== "" ||
        /<img/.test(trimmed);
      if (hasContent) parts.push(`<p>${trimmed}</p>`);
      buffer = "";
    };

    $p.contents().each((_, node) => {
      if (isCardAnchor(node as cheerio.Element)) {
        const href = ($(node).attr("href") ?? "").trim();
        flush();
        parts.push(
          `<div data-link-card data-url="${href.replace(/"/g, "&quot;")}"></div>`,
        );
        return;
      }
      buffer += $.html($(node));
    });
    flush();
    $p.replaceWith(parts.join(""));
  });

  // 画像URLをR2へ書き換え
  $("img").each((_, element) => {
    const $img = $(element);
    const src = $img.attr("src");
    if (src) $img.attr("src", rewriteImageUrl(src));
  });

  return $.html();
};

const sqlQuote = (value: string) => `'${value.replace(/'/g, "''")}'`;

// D1のステートメント長上限回避用の分割
// サロゲートペアを跨がないよう境界を調整
const chunkString = (text: string, maxUnits: number): string[] => {
  const chunks: string[] = [];
  let start = 0;
  while (start < text.length) {
    let end = Math.min(start + maxUnits, text.length);
    const code = text.charCodeAt(end - 1);
    if (code >= 0xd800 && code <= 0xdbff && end < text.length) {
      end -= 1;
    }
    chunks.push(text.slice(start, end));
    start = end;
  }
  return chunks;
};

const LARGE_TEXT_THRESHOLD = 20000;
const CHUNK_UNITS = 20000;
const sqlValue = (value: string | number | null) => {
  if (value === null) return "NULL";
  if (typeof value === "number") return String(value);
  return sqlQuote(value);
};

const out: string[] = [
  "-- Auto-generated by scripts/migrate-microcms-to-d1.ts",
  `-- Source articles: ${articles.length}, tags: ${tags.length}`,
  "",
];

interface ReportRow {
  id: string;
  title: string;
  sourceTextLength: number;
  charCount: number;
  drift: number;
}

const report: ReportRow[] = [];

// 大きな列はUPDATE連結でステートメント長上限を回避
const emitLargeText = (id: string, column: string, text: string) => {
  for (const chunk of chunkString(text, CHUNK_UNITS)) {
    out.push(
      `UPDATE articles SET ${column} = ${column} || ${sqlQuote(chunk)} WHERE id = ${sqlQuote(id)};`,
    );
  }
};

// articles(1記事1ステートメント + 大列は分割UPDATE)
for (const article of articles) {
  const normalized = normalizeHtml(article.content ?? "");
  const doc = generateJSON(normalized, extensions) as TiptapDoc;

  const plainText = extractPlainText(doc);
  const contentJson = JSON.stringify(doc);
  const charCount = countContentCharacters(doc);
  const summary = generateSummary(doc);

  const $source = cheerio.load(article.content ?? "", null, false);
  const sourceTextLength = $source.text().trim().length;
  report.push({
    id: article.id,
    title: article.title,
    sourceTextLength,
    charCount,
    drift: Math.abs(sourceTextLength - charCount),
  });

  const eyecatchKey = article.eyecatch?.url
    ? (imageMap[article.eyecatch.url] ?? null)
    : null;

  const contentInline = contentJson.length <= LARGE_TEXT_THRESHOLD;
  const plainTextInline = plainText.length <= LARGE_TEXT_THRESHOLD;

  const row = [
    sqlValue(article.id),
    sqlValue(article.title ?? ""),
    contentInline ? sqlValue(contentJson) : "''",
    plainTextInline ? sqlValue(plainText) : "''",
    sqlValue(summary),
    sqlValue(charCount),
    sqlValue(eyecatchKey),
    sqlValue(article.eyecatch?.width ?? null),
    sqlValue(article.eyecatch?.height ?? null),
    sqlValue(article.is_no_index ? 1 : 0),
    sqlValue("published"),
    sqlValue(article.publishedAt ?? article.createdAt),
    sqlValue(article.createdAt),
    sqlValue(article.updatedAt),
  ];

  out.push(
    "INSERT OR REPLACE INTO articles (id, title, content, plain_text, summary, char_count, eyecatch_key, eyecatch_width, eyecatch_height, is_no_index, status, published_at, created_at, updated_at) VALUES",
  );
  out.push(`  (${row.join(", ")});`);
  if (!contentInline) emitLargeText(article.id, "content", contentJson);
  if (!plainTextInline) emitLargeText(article.id, "plain_text", plainText);
  out.push("");
}

// tags
if (tags.length > 0) {
  out.push(
    "INSERT OR REPLACE INTO tags (id, name, slug, created_at, updated_at) VALUES",
  );
  out.push(
    tags
      .map(
        (tag) =>
          `  (${sqlQuote(tag.id)}, ${sqlQuote(tag.name)}, ${sqlQuote(tag.slug)}, ${sqlQuote(tag.createdAt)}, ${sqlQuote(tag.updatedAt)})`,
      )
      .join(",\n") + ";",
  );
  out.push("");
}

// article_tags
for (const article of articles) {
  out.push(
    `DELETE FROM article_tags WHERE article_id = ${sqlQuote(article.id)};`,
  );
  const articleTags = article.tags ?? [];
  if (articleTags.length > 0) {
    out.push(
      "INSERT OR REPLACE INTO article_tags (article_id, tag_id, position) VALUES",
    );
    out.push(
      articleTags
        .map(
          (tag, position) =>
            `  (${sqlQuote(article.id)}, ${sqlQuote(tag.id)}, ${position})`,
        )
        .join(",\n") + ";",
    );
  }
}
out.push("");

// images(uploaded_atは参照記事の最古日付)
const CONTENT_TYPE_BY_EXTENSION: Record<string, string> = {
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  png: "image/png",
  gif: "image/gif",
  webp: "image/webp",
  avif: "image/avif",
};

interface ImageMeta {
  uploadedAt: string;
  width: number | null;
  height: number | null;
}

const imageMeta = new Map<string, ImageMeta>();
const addImageMeta = (
  url: string,
  date: string,
  width: number | null,
  height: number | null,
) => {
  const current = imageMeta.get(url);
  if (!current) {
    imageMeta.set(url, { uploadedAt: date, width, height });
    return;
  }
  if (date < current.uploadedAt) current.uploadedAt = date;
  current.width ??= width;
  current.height ??= height;
};

for (const article of articles) {
  const date = article.publishedAt ?? article.createdAt;
  for (const match of (article.content ?? "").matchAll(/<img[^>]*>/g)) {
    const tag = match[0];
    const src = /src="([^"]+)"/.exec(tag)?.[1];
    if (!src || !imageMap[src]) continue;
    addImageMeta(
      src,
      date,
      Number(/width="(\d+)"/.exec(tag)?.[1]) || null,
      Number(/height="(\d+)"/.exec(tag)?.[1]) || null,
    );
  }
  const eyecatchUrl = article.eyecatch?.url;
  if (eyecatchUrl && imageMap[eyecatchUrl]) {
    addImageMeta(
      eyecatchUrl,
      date,
      article.eyecatch?.width ?? null,
      article.eyecatch?.height ?? null,
    );
  }
}

const imageRows = [...imageMeta].map(([url, meta]) => {
  const key = imageMap[url]!;
  const extension = key.split(".").pop() ?? "";
  const filePath = resolve(DATA_DIR, "images", key);
  const size = existsSync(filePath) ? statSync(filePath).size : 0;
  return `  (${sqlQuote(key)}, ${size}, ${sqlValue(meta.width)}, ${sqlValue(meta.height)}, ${sqlValue(CONTENT_TYPE_BY_EXTENSION[extension] ?? null)}, ${sqlQuote(meta.uploadedAt)})`;
});
if (imageRows.length > 0) {
  out.push(
    "INSERT OR REPLACE INTO images (key, size, width, height, content_type, uploaded_at) VALUES",
  );
  out.push(imageRows.join(",\n") + ";");
  out.push("");
}

// pinned
const pinnedIds = (global.pinned_articles ?? []).map((article) => article.id);
out.push(
  `INSERT OR REPLACE INTO site_settings (key, value) VALUES ('pinned_article_ids', ${sqlQuote(JSON.stringify(pinnedIds))});`,
);
out.push("");

writeFileSync(OUTPUT, out.join("\n"), "utf8");
console.log(`Wrote ${OUTPUT}`);

// 検証レポート
console.log("\n=== Validation report ===");
console.log(`Articles: ${articles.length}`);
console.log(`Tags: ${tags.length}`);
console.log(`Pinned articles: ${JSON.stringify(pinnedIds)}`);

const suspicious = report.filter(
  (row) =>
    row.drift > 50 ||
    (row.sourceTextLength > 0 && row.drift / row.sourceTextLength > 0.05),
);
if (suspicious.length === 0) {
  console.log("Articles with large text length drift: none");
} else {
  console.log("Articles with large text length drift (manual check required):");
  for (const row of suspicious) {
    console.log(
      `  ${row.id} "${row.title}" source=${row.sourceTextLength} converted=${row.charCount}`,
    );
  }
}

const unresolvedImages = new Set<string>();
for (const article of articles) {
  for (const match of (article.content ?? "").matchAll(
    /<img[^>]*src="(https:\/\/images\.microcms-assets\.io[^"]+)"/g,
  )) {
    if (!imageMap[match[1]!]) unresolvedImages.add(match[1]!);
  }
}
if (unresolvedImages.size > 0) {
  console.log(`Unresolved image URLs: ${unresolvedImages.size}`);
  for (const url of unresolvedImages) console.log(`  ${url}`);
  process.exitCode = 1;
}
