name: Deploy Workers
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.11.0"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
        env:
          MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN || secrets.NUXT_MICROCMS_SERVICE_DOMAIN }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY || secrets.NUXT_MICROCMS_API_KEY }}
          CONTACT_FORM_WEBHOOK_URI: ${{ secrets.CONTACT_FORM_WEBHOOK_URI || secrets.NUXT_CONTACT_FORM_WEBHOOK_URI }}
          TURNSTILE_SITE_KEY: ${{ secrets.TURNSTILE_SITE_KEY || secrets.NUXT_TURNSTILE_SITE_KEY }}
          TURNSTILE_SECRET_KEY: ${{ secrets.TURNSTILE_SECRET_KEY || secrets.NUXT_TURNSTILE_SECRET_KEY }}
          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID || secrets.NUXT_GA_TRACKING_ID }}
